### ISSUE TITLE
Add hero banner to README

### ISSUE THREAD

**Issue by mpospese** [yml-org/ynetwork-android#1]
Add the following hero banner to the very top of the README (replacing the title line)

```
![Y—Network](https://mpospese.com/wp-content/uploads/2022/08/YNetwork-hero-compact.jpeg)
```

Or otherwise host and attach the following image:
![YNetwork-hero-compact](https://user-images.githubusercontent.com/1037520/186090372-ada57dfc-a266-43df-a4d7-45df8dc575f8.jpeg)

**Comment by kikoso** [comment]
Hi @mpospese . It has been added, thanks for the heads-up!
